# https://aka.ms/yaml

trigger:
- master

jobs:

- job: ShellBuild
  displayName: "Build"
  continueOnError: "true"
  timeoutInMinutes: 5
  variables:
    buildFramework: netcoreapp3.1
  strategy:
    matrix:
      "Linux 3.1 Debug":
        sdkVersion: "3.1.x"
        config: Debug
        imageName: ubuntu-latest
        framework: $(buildFramework)
      "Linux 3.1 Release":
        sdkVersion: "3.1.x"
        config: Release
        imageName: ubuntu-latest
        framework: $(buildFramework)
      "MacOS 3.1 Debug":
        sdkVersion: "3.1.x"
        config: Debug
        imageName: macOS-latest
        framework: $(buildFramework)
      "MacOS 3.1 Release":
        sdkVersion: "3.1.x"
        config: Release
        imageName: macOS-latest
        framework: $(buildFramework)
      "Windows .NET Framework Debug":
        sdkVersion: "3.1.x"
        config: Debug
        imageName: windows-latest
        framework: $(buildFramework)
      "Windows .NET Framework Release":
        sdkVersion: "3.1.x"
        config: Release
        imageName: windows-latest
        framework: $(buildFramework)
  pool:
    vmImage: $(imageName)
  steps:

  - task: UseDotNet@2
    displayName: Install .NET Core SDK $(sdkVersion)
    inputs:
      version: $(sdkVersion)

  - task: ShellScript@2
    displayName: Test Coverage
    inputs:
      scriptPath: ./coverage.sh
      args: "$(framework) $(config)"

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: "**/*.trx"
      failTaskOnFailedTests: true
      buildConfiguration: $(config)
      publishRunAttachments: true

  - task: PublishCodeCoverageResults@1
    displayName: Publish code coverage
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: ./test/TestResults/output/coverage.$(framework).cobertura.xml
