language: csharp

matrix:
  fast_finish: true
  allow_failures:
  - os: osx

  include:
    - os: linux
      dotnet: 3.1
      mono: none
    - os: osx
      dotnet: 3.1.100
      mono: none

branches:
  only:
  - master

script:
  - ./coverage.sh netcoreapp3.1 Release
